### ISSUE TITLE
Cyclic reference error while generating java classes

### ISSUE THREAD

**Issue by somaniab** [atomicbits/scraml#139]
Hello ,

I am getting the following error : 

java: Execution generate-client-sources of goal io.atomicbits:scraml-maven-plugin:0.7.0-M2:scraml failed: Cyclic reference detected when following ParsedTypeReference(NativeId(userSession),NativeId(userSession),None,List(),Fragments(ImplicitId,Map()),RamlModel)

Can you please provide the possible reason behind this?

**Comment by rigolepe** [comment]
Hi,

I believe you have a reference that points back to itself, possibly via
another reference, instead of ending on a real type. Are you using
json-schema or RAML 1.0 types? If you provide a minimal sample, then I can
have a look if you want...

Cheers,
   Peter

Op di 8 aug. 2017 09:52 schreef Abhishek Somani <notifications@github.com>:

**Comment by somaniab** [comment]
The issue was with raml. I have had the same variable type at global level and as well as in the variable name.
